name = "durable-logs"
type = "javascript"
workers_dev = true
compatibility_date = "2021-11-20"
account_id = "ae78534f6c5b673f97bbc5cea1850725"

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
dir = "src"
main = "./shim.mjs"

[durable_objects]
bindings = [
    { name = "COUNTER", class_name = "Counter" }
]

[[migrations]]
tag = "v1" 
new_classes = ["Counter"]
